# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-31 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=8000)),
                ('imgurl', models.CharField(max_length=500)),
                ('dateTime', models.DateField()),
                ('links', models.IntegerField()),
                ('reads', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Commons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('contnet', models.CharField(max_length=500)),
                ('references', models.IntegerField()),
                ('replys', models.IntegerField()),
                ('dateTime', models.DateField()),
                ('links', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
                ('links', models.IntegerField()),
                ('dateTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=8000)),
                ('dateTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themeName', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=8000)),
                ('datetime', models.DateField()),
                ('members', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dateTime', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users'),
        ),
        migrations.AddField(
            model_name='garden',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Theme'),
        ),
        migrations.AddField(
            model_name='commons',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users'),
        ),
        migrations.AddField(
            model_name='commons',
            name='blogs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blogs'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='garden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Garden'),
        ),
    ]
