# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-08 09:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='garden',
        ),
        migrations.RemoveField(
            model_name='commons',
            name='author',
        ),
        migrations.RemoveField(
            model_name='commons',
            name='blogs',
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='author',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Commons',
        ),
        migrations.DeleteModel(
            name='Discuss',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
