# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-08 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180408_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=8000)),
                ('imgurl', models.CharField(max_length=500)),
                ('dateTime', models.DateField()),
                ('links', models.IntegerField()),
                ('reads', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users')),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Garden')),
            ],
        ),
        migrations.CreateModel(
            name='Commons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('contnet', models.CharField(max_length=500)),
                ('references', models.IntegerField()),
                ('replys', models.IntegerField()),
                ('dateTime', models.DateField()),
                ('links', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users')),
                ('blogs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentId', models.IntegerField()),
                ('contnet', models.CharField(max_length=500)),
                ('references', models.IntegerField()),
                ('links', models.IntegerField()),
                ('dateTime', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('links', models.IntegerField()),
                ('dateTime', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('themeName', models.CharField(max_length=50)),
                ('introduce', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=8000)),
                ('datetime', models.DateField()),
                ('members', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users')),
            ],
        ),
        migrations.AddField(
            model_name='discusstopic',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Theme'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.DiscussTopic'),
        ),
    ]
