# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-04-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20180408_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='garden',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(),
        ),
    ]
