# Generated by Django 2.0.4 on 2018-04-21 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20180409_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('subtitle', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('imgurl', models.CharField(max_length=500)),
                ('dateTime', models.DateTimeField()),
                ('links', models.IntegerField()),
                ('reads', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='discuss',
            name='contnet',
        ),
        migrations.RemoveField(
            model_name='discusstopic',
            name='theme',
        ),
        migrations.AddField(
            model_name='commons',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='discuss',
            name='content',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='garden',
            name='cover_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='introduce',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='dateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='commons',
            name='dateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='dateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='discusstopic',
            name='dateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='garden',
            name='dateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='theme',
            name='datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='dateTime',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='themeblogs',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Users'),
        ),
        migrations.AddField(
            model_name='themeblogs',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Theme'),
        ),
        migrations.AddField(
            model_name='discusstopic',
            name='themeBlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blogs.ThemeBlogs'),
        ),
    ]
