# Generated by Django 2.0 on 2018-05-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20180421_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
