# Generated by Django 2.0 on 2018-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20180504_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='url',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
