# Generated by Django 2.0 on 2018-05-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_theme_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='icon',
        ),
    ]
